// lang-en.ts
export const LANG_EN_TRANS = {
    "Login": "Login",
    "Password": "Password",
	"Enter": "Enter",
	"is required": "is required",	
	"Home": "Home",
	"About": "About",
	"Info": "Info",
	"Home page": "Home page",
	"About page": "About page",
	"Info page": "Info page",
	"Exit": "Exit",
	"Hi": "Hi",
	"Affairs list": "Affairs list",
	"Register": "Register",	
	"First Name": "First Name",	
	"Last Name": "Last Name",	
	"Cancel": "Cancel",	
	"Learn Angular 2": "Learn Angular 2",		
	"Success add": "Success add",
	"Success delete": "Success delete",	
	"Language": "Language",
	"Add": "Add",
	"Delete": "Delete",
	"Save": "Save",
	"Edit": "Edit",
	"Text": "Text",
	"Date": "Date",
	"First component": "First component",
	"Second component": "Second component",
	"Three component": "Three component",
	"Email": "Email",
	"Answer": "Answer",
	"Question": "Question",
	"Interview": "Interview"
	
};