// lang-bs.ts
export const LANG_BS_TRANS = {
    "Login": "Логин",
    "Password": "Пароль",
	"Enter": "Керер урыны",
	"is required": "тултырыу кәрәк",
	"Home": "Баш бит",
	"About": "Сайт тураһында",
	"Info": "Мәғлүмәт",
	"Home page": "Баш бит",
	"About page": "Сайт тураһында бит",
	"Info page": "Мәғлүмәт бите",
	"Exit": "Сығыу",
	"Hi": "Сәләм",
	"Affairs list": "әшләр",
	"Register": "Теркәү",
	"First Name": "Исем",	
	"Last Name": "Фамилия",	
	"Cancel": "Ғәмәлгә ашырмау",	
	"Learn Angular 2": "Angular 2 өйрәнеү",		
	"Success add": "Уңышлы өҫтәлгән",		
	"Success delete": "Уңышлы бөтөрелгән",	
	"Language": "Тел",
	"Add": "Оҫтәргә",
	"Delete": "Бөтөргә",
	"Save": "Сохранить",
	"Edit": "Изменить",
	"Text": "Текст",
	"Date": "Дата",
	"First component": "Беренсе компонент",
	"Second component": "Икенсе компонент",
	"Three component": "Осөнсө компонент"			
};