// lang-ru.ts
export const LANG_RU_TRANS = {
    "Login": "Имя пользователя",
    "Password": "Пароль",
	"Enter": "Вход",
	"is required": "обязательно для заполнения",
	"Home": "Домашняя",
	"About": "О сайте",
	"Info": "Информация",
	"Home page": "Домашняя страница",
	"About page": "Страница о сайте",
	"Info page": "Информационная страница",
	"Exit": "Выход",
	"Hi": "Привет",
	"Affairs list": "Список дел",
	"Register": "Регистрация",
	"First Name": "Имя",	
	"Last Name": "Фамилия",	
	"Cancel": "Отмена",	
	"Learn Angular 2": "Изучение Angular 2",		
	"Success add": "Успешно добавлено",		
	"Success delete": "Успешно удалено",	
	"Language": "Язык",
	"Add": "Добавить",
	"Delete": "Удалить",
	"Save": "Сохранить",
	"Edit": "Изменить",
	"Text": "Текст",
	"Date": "Дата",
	"First component": "Первый компонент",
	"Second component": "Второй компонент",
	"Three component": "Третий компонент"	
};